### ISSUE TITLE
Pikcer bug

### ISSUE THREAD

**Issue by Ijeal** [RavishaHesh/RandomNumberPicker#1]
Hey,there! I think there is an bug in following code:
					var number = chance.integer({
						min: Math.min.apply(null, diff),
						max: Math.max.apply(null, diff)
					});
It should be like this:
					var number = chance.integer({
						min: 0,
						max: diff.length-1
					});
					setTimeout(() => {
						app.selected_number = diff[number];
						app.excluded_numbers.push(app.selected_number);
						$('#ex-btn-' + diff[number]).prop('class', 'btn btn-danger');
						app.shuffling = false;
						app.is_number_picked = true;					
					}, 5000);
And I create a new project based on your code in https://github.com/Ijeal/LuckyNumberPicker.git and quote your project in the README.MD,  please ping me if you have any concerns about this.

**Comment by RavishaHesh** [comment]
Since the start value of the range is dynamic, you can't set it to "0". And also to get max value from `diff.length-1` first, you have to sort the array

**Comment by Ijeal** [comment]
Oh, I think we may understand the chance.integer({min: -20, max: 20}) API differently, here is the offical api description:
_These min and max are inclusive, so they are included in the range. This means chance.integer({min: -2, max: 2}); would return either -2, -1, 0, 1, or 2._
Anyway, thanks for your project, it really save my time.
